export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const GET_CURSO = 'GET_CURSO';
export const GET_CURSOS = 'GET_CURSOS';
export const ADD_CURSO = 'ADD_CURSO';
export const DELETE_CURSO = 'DELETE_CURSO';
export const UPDATE_CURSO = 'UPDATE_CURSO';
export const MATRICULARSE_CURSO = 'MATRICULARSE_CURSO';
export const GET_CURSOS_USUARIO = 'GET_CURSOS_USUARIO';

export const GET_PRACTICAS = 'GET_PRACTICAS';
export const GET_PRACTICAS_BY_USER = 'GET_PRACTICAS_BY_USER';
export const GET_PRACTICAS_BY_COURSE = 'GET_PRACTICAS_BY_COURSE';
export const GET_PRACTICAS_BY_COURSE_ESTUDIANTES = 'GET_PRACTICAS_BY_COURSE_ESTUDIANTES';
export const GET_PRACTICAS_BY_USER_TEACHER = 'GET_PRACTICAS_BY_USER_TEACHER';
export const GET_PRACTICA = 'GET_PRACTICA';
export const ADD_PRACTICA = 'ADD_PRACTICA';
export const UPDATE_PRACTICA = 'UPDATE_PRACTICA';
export const DELETE_PRACTICA = 'DELETE_PRACTICA';
export const PRACTICA_ERROR = 'PRACTICA_ERROR';
export const CLEAR_PRACTICA = 'CLEAR_PRACTICA';
export const SET_LOADING = 'SET_LOADING';


export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_USER = 'UPDATE_USER';
export const FILTER_USERS = 'FILTER_USERS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const USER_ERROR = 'USER_ERROR';
export const CLEAR_USERS = 'CLEAR_USERS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';

